estimator:
  pickle: model.pickl

strategy:
  name: grid

search_space:
  filter__fraction:
    min: 0.005
    max: 1
    num: 5
    var: float
    warp: log

  cluster__n_bins_per_feature:
    min: 10
    max: 1000
    num: 100
    var_type: int
    type: jump

  msm__score_k:
    min: 2
    max: 6
    type: int

  msm__score_method:
    choices:
      - vamp1
      - vamp2
      - vampe
    type: enum

cv: 5

dataset_loader:
  name: numpy
  params:
    filenames: ./data/*.npy
trials:
    uri: sqlite:///osprey-trials.db

random_seed: 42
