estimator:
  pickle: model.pickl

strategy:
  name: grid

search_space:

  cluster__n_bins_per_feature:
    min: 10
    max: 1000
    num: 100
    var_type: int
    type: jump

  msm__score_k:
    min: 2
    max: 6
    num: 5
    var_type: int
    type: jump

  msm__score_method:
    choices:
      - vamp1
      - vamp2
      - vampe
    type: enum

cv: 5

dataset_loader:
  name: numpy
  params:
    filenames: ./data/000.5pc/*.npy

trials:
    uri: sqlite:///osprey-trials.db
    project_name: 000.5pc

random_seed: 42
